language: python

cache:
  - apt
  - pip
python:
  - 2.7
  - 3.6
  - 3.8
  - pypy
  - pypy3
env:
    - ZMQ=
    - ZMQ=bundled
before_install:
  - sudo add-apt-repository -y ppa:anton+/dnscrypt
  - sudo apt-get update
  - |
    # install libzmq, libsodium unless zmq=bundled
    if [[ $ZMQ != bundled ]]; then
      sudo apt-get install -y -qq libzmq3-dev libsodium-dev
    fi
  - |
    # install cython unless pypy
    if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      pip install cython
    fi
  - |
    # build libzmq
    if [[ ! -z "$ZMQ" && $ZMQ != bundled ]]; then
      wget https://github.com/zeromq/$ZMQ/archive/master.zip -O libzmq.zip
      unzip libzmq.zip
      pushd "$ZMQ-master"
      ./autogen.sh
      ./configure --enable-drafts
      make -j
      sudo make install
      sudo ldconfig
      popd
      export ZMQ=/usr/local
      export ZMQ_DRAFT_API=1
    fi
  - pip install -r test-requirements.txt
  - |
    # install pinned tornado
    if [[ "$TORNADO" == "master" ]]; then
      pip install https://github.com/tornadoweb/tornado/archive/master.zip
    elif [[ "$TORNADO" == "none" ]]; then
      pip uninstall -yq tornado
    elif [[ ! -z "$TORNADO" ]]; then
      pip install tornado==${TORNADO}
    fi
  - pip freeze

install:
  - python setup.py build_ext --inplace --zmq=$ZMQ

matrix:
  include:
    - python: pypy
      env: ZMQ=bundled
    - python: 3.8
      env: ZMQ=
    - python: 3.8
      env: ZMQ=bundled
    - python: 3.7
      env: ZMQ=
    - python: 3.7
      env: ZMQ=bundled
    - python: 3.6
      env:
        - ZMQ=
        - TORNADO=none
    - python: 3.6
      env:
        - ZMQ=
        - TORNADO=master
    - python: 3.6
      env:
        - ZMQ=
        - TORNADO=4.5.*
    - python: 2.7
      env:
        - ZMQ=
        - TORNADO=4.5.*
    - python: 3.5
      env: ZMQ=libzmq
    - python: 3.4
      env: ZMQ=zeromq4-x
    - python: 3.4
      env: ZMQ=zeromq4-1
    - python: 3.4
      env: ZMQ=zeromq3-x
    - python: 3.3
      dist: trusty
      env: ZMQ=
    - python: nightly
      env: ZMQ=
    - python: nightly
      env: ZMQ=bundled
  allow_failures:
    - env: ZMQ=libzmq
    - python: nightly

script: travis_retry python setup.py test
